/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';


import {
  FighterSkeleton,
} from './models/fighter/fighter-skeleton';
import {
  RoundNews,
} from './models/game/roundNews';
import {
  Manager,
} from './server/game/manager/manager';
import {
  EventEmitter,
} from '@stencil/core';
import {
  ClientToServer,
} from './models/app/clientToServer';
import {
  ConnectionStates,
} from './types/app/connectionStates';
import {
  Fighter,
} from './server/game/fighter/fighter';


export namespace Components {

  interface GameComponent {}
  interface GameComponentAttributes extends StencilHTMLAttributes {}

  interface FightComponent {}
  interface FightComponentAttributes extends StencilHTMLAttributes {}

  interface FighterComponent {
    'fighter': FighterSkeleton;
  }
  interface FighterComponentAttributes extends StencilHTMLAttributes {
    'fighter'?: FighterSkeleton;
  }

  interface NewsComponent {
    'roundNews': RoundNews[];
  }
  interface NewsComponentAttributes extends StencilHTMLAttributes {
    'roundNews'?: RoundNews[];
  }

  interface PostFightComponent {}
  interface PostFightComponentAttributes extends StencilHTMLAttributes {}

  interface PreFightComponent {
    'allFighters': FighterSkeleton[];
    'manager': Manager;
    'roundFighters': FighterSkeleton[];
    'timeRemaining': number;
  }
  interface PreFightComponentAttributes extends StencilHTMLAttributes {
    'allFighters'?: FighterSkeleton[];
    'manager'?: Manager;
    'onClientToServer'?: (event: CustomEvent<ClientToServer>) => void;
    'roundFighters'?: FighterSkeleton[];
    'timeRemaining'?: number;
  }

  interface RoundComponent {
    'allFighters': FighterSkeleton[];
    'manager': Manager;
  }
  interface RoundComponentAttributes extends StencilHTMLAttributes {
    'allFighters'?: FighterSkeleton[];
    'manager'?: Manager;
  }

  interface SetNameComponent {}
  interface SetNameComponentAttributes extends StencilHTMLAttributes {}

  interface NotConnectedComponent {}
  interface NotConnectedComponentAttributes extends StencilHTMLAttributes {}

  interface PreGameLobbyComponent {}
  interface PreGameLobbyComponentAttributes extends StencilHTMLAttributes {}

  interface PreGameComponent {
    'connectionStatus': ConnectionStates;
    'name': string;
  }
  interface PreGameComponentAttributes extends StencilHTMLAttributes {
    'connectionStatus'?: ConnectionStates;
    'name'?: string;
  }

  interface DanielsFightingPit {}
  interface DanielsFightingPitAttributes extends StencilHTMLAttributes {}

  interface FighterModel {
    'fighter': Fighter;
  }
  interface FighterModelAttributes extends StencilHTMLAttributes {
    'fighter'?: Fighter;
  }
}

declare global {
  interface StencilElementInterfaces {
    'GameComponent': Components.GameComponent;
    'FightComponent': Components.FightComponent;
    'FighterComponent': Components.FighterComponent;
    'NewsComponent': Components.NewsComponent;
    'PostFightComponent': Components.PostFightComponent;
    'PreFightComponent': Components.PreFightComponent;
    'RoundComponent': Components.RoundComponent;
    'SetNameComponent': Components.SetNameComponent;
    'NotConnectedComponent': Components.NotConnectedComponent;
    'PreGameLobbyComponent': Components.PreGameLobbyComponent;
    'PreGameComponent': Components.PreGameComponent;
    'DanielsFightingPit': Components.DanielsFightingPit;
    'FighterModel': Components.FighterModel;
  }

  interface StencilIntrinsicElements {
    'game-component': Components.GameComponentAttributes;
    'fight-component': Components.FightComponentAttributes;
    'fighter-component': Components.FighterComponentAttributes;
    'news-component': Components.NewsComponentAttributes;
    'post-fight-component': Components.PostFightComponentAttributes;
    'pre-fight-component': Components.PreFightComponentAttributes;
    'round-component': Components.RoundComponentAttributes;
    'set-name-component': Components.SetNameComponentAttributes;
    'not-connected-component': Components.NotConnectedComponentAttributes;
    'pre-game-lobby-component': Components.PreGameLobbyComponentAttributes;
    'pre-game-component': Components.PreGameComponentAttributes;
    'daniels-fighting-pit': Components.DanielsFightingPitAttributes;
    'fighter-model': Components.FighterModelAttributes;
  }


  interface HTMLGameComponentElement extends Components.GameComponent, HTMLStencilElement {}
  var HTMLGameComponentElement: {
    prototype: HTMLGameComponentElement;
    new (): HTMLGameComponentElement;
  };

  interface HTMLFightComponentElement extends Components.FightComponent, HTMLStencilElement {}
  var HTMLFightComponentElement: {
    prototype: HTMLFightComponentElement;
    new (): HTMLFightComponentElement;
  };

  interface HTMLFighterComponentElement extends Components.FighterComponent, HTMLStencilElement {}
  var HTMLFighterComponentElement: {
    prototype: HTMLFighterComponentElement;
    new (): HTMLFighterComponentElement;
  };

  interface HTMLNewsComponentElement extends Components.NewsComponent, HTMLStencilElement {}
  var HTMLNewsComponentElement: {
    prototype: HTMLNewsComponentElement;
    new (): HTMLNewsComponentElement;
  };

  interface HTMLPostFightComponentElement extends Components.PostFightComponent, HTMLStencilElement {}
  var HTMLPostFightComponentElement: {
    prototype: HTMLPostFightComponentElement;
    new (): HTMLPostFightComponentElement;
  };

  interface HTMLPreFightComponentElement extends Components.PreFightComponent, HTMLStencilElement {}
  var HTMLPreFightComponentElement: {
    prototype: HTMLPreFightComponentElement;
    new (): HTMLPreFightComponentElement;
  };

  interface HTMLRoundComponentElement extends Components.RoundComponent, HTMLStencilElement {}
  var HTMLRoundComponentElement: {
    prototype: HTMLRoundComponentElement;
    new (): HTMLRoundComponentElement;
  };

  interface HTMLSetNameComponentElement extends Components.SetNameComponent, HTMLStencilElement {}
  var HTMLSetNameComponentElement: {
    prototype: HTMLSetNameComponentElement;
    new (): HTMLSetNameComponentElement;
  };

  interface HTMLNotConnectedComponentElement extends Components.NotConnectedComponent, HTMLStencilElement {}
  var HTMLNotConnectedComponentElement: {
    prototype: HTMLNotConnectedComponentElement;
    new (): HTMLNotConnectedComponentElement;
  };

  interface HTMLPreGameLobbyComponentElement extends Components.PreGameLobbyComponent, HTMLStencilElement {}
  var HTMLPreGameLobbyComponentElement: {
    prototype: HTMLPreGameLobbyComponentElement;
    new (): HTMLPreGameLobbyComponentElement;
  };

  interface HTMLPreGameComponentElement extends Components.PreGameComponent, HTMLStencilElement {}
  var HTMLPreGameComponentElement: {
    prototype: HTMLPreGameComponentElement;
    new (): HTMLPreGameComponentElement;
  };

  interface HTMLDanielsFightingPitElement extends Components.DanielsFightingPit, HTMLStencilElement {}
  var HTMLDanielsFightingPitElement: {
    prototype: HTMLDanielsFightingPitElement;
    new (): HTMLDanielsFightingPitElement;
  };

  interface HTMLFighterModelElement extends Components.FighterModel, HTMLStencilElement {}
  var HTMLFighterModelElement: {
    prototype: HTMLFighterModelElement;
    new (): HTMLFighterModelElement;
  };

  interface HTMLElementTagNameMap {
    'game-component': HTMLGameComponentElement
    'fight-component': HTMLFightComponentElement
    'fighter-component': HTMLFighterComponentElement
    'news-component': HTMLNewsComponentElement
    'post-fight-component': HTMLPostFightComponentElement
    'pre-fight-component': HTMLPreFightComponentElement
    'round-component': HTMLRoundComponentElement
    'set-name-component': HTMLSetNameComponentElement
    'not-connected-component': HTMLNotConnectedComponentElement
    'pre-game-lobby-component': HTMLPreGameLobbyComponentElement
    'pre-game-component': HTMLPreGameComponentElement
    'daniels-fighting-pit': HTMLDanielsFightingPitElement
    'fighter-model': HTMLFighterModelElement
  }

  interface ElementTagNameMap {
    'game-component': HTMLGameComponentElement;
    'fight-component': HTMLFightComponentElement;
    'fighter-component': HTMLFighterComponentElement;
    'news-component': HTMLNewsComponentElement;
    'post-fight-component': HTMLPostFightComponentElement;
    'pre-fight-component': HTMLPreFightComponentElement;
    'round-component': HTMLRoundComponentElement;
    'set-name-component': HTMLSetNameComponentElement;
    'not-connected-component': HTMLNotConnectedComponentElement;
    'pre-game-lobby-component': HTMLPreGameLobbyComponentElement;
    'pre-game-component': HTMLPreGameComponentElement;
    'daniels-fighting-pit': HTMLDanielsFightingPitElement;
    'fighter-model': HTMLFighterModelElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
